provider: aws

backend:
  type: s3
  config:
     bucket: ${AWS_REGION}-${AWS_ACCOUNT_ID}-terraform-state
     key: ${GIT_REPOSITORY}
     region: ${AWS_REGION}
     dynamodb_table: terraform-statelock
     encrypt: true
     kms_key_id: arn:aws:kms:${AWS_REGION}:${AWS_ACCOUNT_ID}:alias/${AWS_REGION}-${AWS_ACCOUNT_ID}-terraform-state

variables:
  git_repository: ${GITHUB_REPOSITORY}
  commit_hash: "${GIT_COMMIT_SHA}"
  allowed_cidr_blocks: "${ALLOWED_CIDR_BLOCKS}"
  public_hosted_zone_name: "${PUBLIC_HOSTED_ZONE_NAME}"
  sample_ftps_entra_client_id: "${SAMPLE_FTPS_ENTRA_CLIENT_ID}"
  sample_sftp_entra_client_id: "${SAMPLE_SFTP_ENTRA_CLIENT_ID}"
  sample_sftp_ssh_public_key: "${SAMPLE_SFTP_SSH_PUBLIC_KEY}"
  auth_verbose_logging: "${AUTH_VERBOSE_LOGGING}"
  dr_mode: "${DR_MODE}"
